<h3>Contact Information</h3>
<table border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td>
<p align="left" style="font-size: 16px; line-height: 26px;">

<br><br>
&nbsp; &nbsp; &nbsp; <b>A Better Pruning</b><br>
<!--
&nbsp; &nbsp; &nbsp; 117 NW 60th Street<br>
&nbsp; &nbsp; &nbsp; Seattle, WA &nbsp; 98107<br>
-->
<br>
&nbsp; &nbsp; &nbsp; Phone: &nbsp; (206) 782-2667<br>
<br>
&nbsp; &nbsp; &nbsp; Email: &nbsp; <script type="text/javascript" src="email.js"></script><br>
<br>
&nbsp; &nbsp; &nbsp; Web: &nbsp;<a href="http://www.abetterpruning.com">www.abetterpruning.com</a><br>
<br>
&nbsp; &nbsp; &nbsp; Owner: &nbsp;Michael Berry<br>


<br>

    </td>
  </tr>
</table>
