          </td>
        </tr>
      </table>
    </td>
  </tr>

  <tr height="32"> 
    <td class="bottombar" align="right" valign="middle" colspan="3" background="images/grn_bot.gif">
      <table border="0" cellspacing="0" cellpadding="0" width="100%">
        <tr>
          <td class="bottombar" align="center">
      A Better Pruning / Michael's Landscaping -
      (206) 782-2667</td>
          <td width="20">
<!-- sitemeter TBD -->
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>

</body>
</html>
