
<h3>Photo Gallery</h3>
<center>
<p><br>
<b><i>Before...</b></i><br>
<img class="portrait" src="images/house4_before_643_413.jpg" width="643" height="413" align="center"> 
<br><br>
<b><i>After...</b></i><br>
<img class="portrait" src="images/house4_after_610_356.jpg" width="610" height="356" align="center"> 
<br><br>
<hr>
<br>
<img class="portrait" src="images/house1_487_366.jpg" width="487" height="366" align="center"> 
<br><br>
<img class="portrait" src="images/house3_469_352.jpg" width="469" height="352" align="center"> 
</center>