<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>

<head>
<title>A Better Pruning - Michael's Landscaping - Seattle Landscaping Services (206) 782-2667</title>
<meta http-equiv="description" content="Seattle landscaping">
<meta http-equiv="keywords" content="tree removal, fertilizing">
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta name="rating" content="general">
<meta name="robots" content="all">
<link rel="stylesheet" href="style.css" type="text/css">
<script type="text/javascript" language="JavaScript">
<!--
<!--
function MM_reloadPage(init) {  //reloads the window if Nav4 resized
  if (init==true) with (navigator) {if ((appName=="Netscape")&&(parseInt(appVersion)==4)) {
    document.MM_pgW=innerWidth; document.MM_pgH=innerHeight; onresize=MM_reloadPage; }}
  else if (innerWidth!=document.MM_pgW || innerHeight!=document.MM_pgH) location.reload();
}
MM_reloadPage(true);
// -->
//-->
</script>
</head>

<body marginwidth="0" marginheight="0">

<?php
settype($index, "integer"); 
settype($gallery, "integer"); 
settype($specials, "integer"); 
settype($resources, "integer"); 
settype($contact, "integer"); 
?>

<table width="100%" height="100%" border="0" cellspacing="0" cellpadding="0">
  <tr height="1">
    <td bgcolor="#336633" width="250"><img src="images/blank.gif" height="1" width="150"></td>
    <td bgcolor="#336633" width="1%"><img src="images/blank.gif" height="1"></td>
    <td bgcolor="#336633" width="98%"><img src="images/blank.gif" height="1"></td>
  </tr>

  <tr height="60">
    <td nowrap colspan="3" bgcolor="#336633" valign="middle" align="center"
      >
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td><h1>&nbsp; &nbsp; A Better Pruning / Michael's Landscaping</h1></td>
          <td align="right"><script
        type="text/javascript"
        src="http://www.angieslist.com/webbadge/insertwebbadge.js?bid=2a93ce413e060837343bc7f4cde0e1e2">
        </script><script type="text/javascript">if (BADGEBOX) BADGEBOX.PlaceBadge();</script>
        <noscript><div id="ssanslnk"><a
        href="http://www.angieslist.com/companylist/us/wa/seattle/landscaping.aspx"
        title="Angie's List Super Service Award winner">SEATTLE landscaping</a></div></noscript></td>
       <!--<img src="images\angie.png" title="Angie's List Super Service Award winner">-->
          </td>
        </tr>
      </table>
    </td>
  </tr>

  <tr height="7"> 
    <td colspan="3" background="images/drp_shadow.gif"><img
      src="images/blank.gif" height="7"></td>
  </tr>

  <tr valign="top">

    <td background="images/lt_grn_bgd.gif"><img src="images/blank.gif" height="7">

      <table border="0" cellspacing="10" cellpadding="0">

        <tr> 
          <td class="navbar" width="25" height="30" align="center">&nbsp;
            <?php
              if ($index) {
            ?>
              <img src="images/arrow_right.gif" width="10" height="12">
            <?php
              }
            ?>
          </td>
          <td class="navbar">&nbsp;<a
            href="index.php" onFocus="if(this.blur)this.blur()"><nobr>Home</nobr></a></td>
        </tr>

        <tr> 
          <td class="navbar" height="30" align="center">&nbsp;
            <?php
              if ($gallery) {
            ?>
              <img src="images/arrow_right.gif" width="10" height="12">
            <?php
              }
            ?>
          </td>
          <td class="navbar">&nbsp;<a
            href="gallery.php" onFocus="if(this.blur)this.blur()"><nobr>Photo Gallery</nobr></a></td>
        </tr>


        <tr> 
          <td class="navbar" height="30" align="center">&nbsp;
            <?php
              if ($specials) {
            ?>
              <img src="images/arrow_right.gif" width="10" height="12">
            <?php
              }
            ?>
          </td>
          <td class="navbar">&nbsp;<a
            href="specials.php" onFocus="if(this.blur)this.blur()"><nobr>Specials</nobr></a></td>
        </tr>


        <tr> 
          <td class="navbar" height="30" align="center">&nbsp;
            <?php
              if ($resources) {
            ?>
              <img src="images/arrow_right.gif" width="10" height="12">
            <?php
              }
            ?>
          </td>
          <td class="navbar">&nbsp;<a
            href="resources.php" onFocus="if(this.blur)this.blur()"><nobr>Resources</nobr></a></td>
        </tr>


        <tr> 
          <td class="navbar" height="30" align="center">&nbsp;
            <?php
              if ($contact) {
            ?>
              <img src="images/arrow_right.gif" width="10" height="12">
            <?php
              }
            ?>
          </td>
          <td class="navbar">&nbsp;<a
            href="contact.php" onFocus="if(this.blur)this.blur()"><nobr>Contact Info</nobr></a></td>
        </tr>


      </table>

    </td>

    <td colspan="2" align="center" valign="top">
      <table border="0" cellspacing="30" cellpadding="0" width="100%">
        <tr valign="top">  
          <td align="center">

