<p>Specializing in the highest quality of:

<ul>
<li>Landscaping</li>
<li>Pruning</li>
<li>Tree Removal</li>
<li>Hedges</li>
<li>Bark Application</li>
<li>Pressure Washing</li>
<li>Lawn and Yard Work</li>
<li>Overgrown Yard Restoration</li>
<li>Blackberry Removal</li>
<li>Renovations</li>
<li>Regular Yard Maintenance</li>
<li>Lawn Mowing</li>
<li>Weeding</li>
</ul>

<p align="left"><i>This includes great clean-up with any work done!</i><br>
<br>

Serving &nbsp;Seattle, Phinney Ridge, Ballard, Magnolia, Queen Anne, View Ridge, Broadview, Shoreline, Laurelhurst, Blue Ridge, Wedgewood, Ravenna, Green Lake, Wallingford, University District, etc.<br>
<br> 

<ul>
<li>Free Estimates</li>
<li>Satisfaction Guaranteed!</li>
<li>5% Senior Discount</li>
<li>Owner/Operator: no subcontractors used</li>
<li>Licensed and insured</li>
<li>Practicing arborculture and offering green services</li>
<li>Listed at: <a href="http://www.angieslist.com/companylist/us/wa/seattle/a-better-pruning-michaels-landscaping-reviews-368427.aspx">AngiesList.com</a>.</li>
</ul>

<p>
Operating Hours: &nbsp;Mon-Sat 7:00 AM-8:00 PM <i>(also 24 hour emergency service)</i><br>
<br>

